name: Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'sheikin'
          cache: maven

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
